versions:
  "1.92.6":
    folder: all
  "1.92.6-docking":
    folder: all
  "1.91.8":
    folder: all
  "1.91.8-docking":
    folder: all
  "1.90.9":
    folder: all
  "1.90.9-docking":
    folder: all
  "1.90.5":
    folder: all
  "1.90.5-docking":
    folder: all
